[package]
name = "train"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
ratatui = "0.29.0"
tabled = "0.20.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
tokio = { version = "1.48.0", features = ["full"] }
